from enum import Enum

class SystemAction(str, Enum):
    INSERT = "INSERT"
    UPDATE = "UPDATE"
    DELETE = "DELETE"
    LOGIN = "LOGIN"
    LOGOUT = "LOGOUT"
    CLOCK_IN = "CLOCK_IN"
    CLOCK_OUT = "CLOCK_OUT"
    PASSWORD_CHANGE = "password_change"
    PROFILE_UPDATE = "profile_update"
    DATA_EXPORT = "data_export"
    DATA_IMPORT = "data_import"
    ASSIGN_ROLE = "assign_role"
    REVOKE_ROLE = "revoke_role"
    VIEW_REPORT = "view_report"
    APPROVE_LEAVE = "approve_leave"
    REJECT_LEAVE = "reject_leave"
    CREATE_DEPARTMENT = "create_department"
    DELETE_DEPARTMENT = "delete_department"
    TOKEN_REFRESH = "token_refresh"

class AttendanceStatus(str, Enum):
    PRESENT = "present"
    ABSENT = "absent"
    LATE = "late"
    EARLY_DEPARTURE = "early_departure"
    ON_LEAVE = "on_leave"
    HALF_DAY = "half_day"
    SICK = "sick"

class LeaveRequestStatus(str, Enum):
    DRAFT = "draft"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    CANCELLED = "cancelled"
    COMPLETED = "completed"

class LeaveType(str, Enum):
    ANNUAL = "annual"
    SICK = "sick"
    MATERNITY = "maternity"
    PATERNITY = "paternity"
    EMERGENCY = "emergency"
    UNPAID = "unpaid"
    CASUAL = "casual"
    COMPENSATORY = "compensatory"
    BEREAVEMENT = "bereavement"
    LEAVE_OF_ABSENCE = "leave_of_absence"
    PUBLIC_HOLIDAY = "public_holiday"

class CorrectionStatus(str, Enum):
    DRAFT = "draft"
    UNDER_REVIEW = "under_review"
    APPROVED = "approved"
    REJECTED = "rejected"
    CANCELLED = "cancelled"
    COMPLETED = "completed"

class EmployeeType(str, Enum):
    FULL_TIME = "full_time"
    PART_TIME = "part_time"
    CONTRACT = "contract"
    INTERN = "intern"
    TEMPORARY = "temporary"

class ShiftType(str, Enum):
    MORNING = "morning"
    AFTERNOON = "afternoon"
    NIGHT = "night"
    FLEXIBLE = "flexible"
    SPLIT = "split"

class Permission(str, Enum):
    # Employee permissions
    CLOCK_IN = "clock_in"
    CLOCK_OUT = "clock_out"
    REQUEST_LEAVE = "request_leave"
    VIEW_LEAVE_BALANCE = "view_leave_balance"
    VIEW_OWN_ATTENDANCE = "view_own_attendance"
    CREATE_LEAVE_REQUEST = "create_leave_request"
    CREATE_TIME_CORRECTION = "create_time_correction"
    VIEW_TIME_CORRECTION = "view_time_correction"
    REFRESH_TOKEN = "refresh_token"
    VIEW_HOLIDAY = "view_holiday"
    
    # Manager permissions
    APPROVE_LEAVE = "approve_leave"
    MANAGE_OVERTIME = "manage_overtime"
    GENERATE_REPORTS = "generate_reports"
    VIEW_TEAM_ATTENDANCE = "view_team_attendance"
    VIEW_LEAVE_APPROVAL = "view_leave_approval"
    CREATE_OVERTIME_RECORD = "create_overtime_record"
    VIEW_OVERTIME_RECORD = "view_overtime_record"
    VIEW_TEAM_OVERTIME_RECORDS = "view_team_overtime_records"
    UPDATE_TIME_CORRECTION = "update_time_correction"
    
    # HR permissions
    MANAGE_EMPLOYEES = "manage_employees"
    CREATE_USER = "create_user"
    VIEW_USER = "view_user"
    UPDATE_USER = "update_user"
    DELETE_USER = "delete_user"
    VIEW_ALL_ATTENDANCE = "view_all_attendance"
    MANAGE_LEAVE_POLICIES = "manage_leave_policies"
    GENERATE_COMPLIANCE_REPORTS = "generate_compliance_reports"
    UPDATE_LEAVE_BALANCE = "update_leave_balance"
    CREATE_LEAVE_POLICY = "create_leave_policy"
    VIEW_LEAVE_POLICY = "view_leave_policy"
    UPDATE_LEAVE_POLICY = "update_leave_policy"
    DELETE_LEAVE_POLICY = "delete_leave_policy"
    CREATE_HOLIDAY = "create_holiday"
    UPDATE_HOLIDAY = "update_holiday"
    DELETE_HOLIDAY = "delete_holiday"
    CREATE_SHIFT_PATTERN = "create_shift_pattern"
    VIEW_SHIFT_PATTERN = "view_shift_pattern"
    UPDATE_SHIFT_PATTERN = "update_shift_pattern"
    DELETE_SHIFT_PATTERN = "delete_shift_pattern"
    
    # Admin permissions
    VIEW_LOGS = "view_logs"
    MANAGE_ROLES = "manage_roles"
    CREATE_USER_ROLE = "create_user_role"
    VIEW_USER_ROLE = "view_user_role"
    UPDATE_USER_ROLE = "update_user_role"
    DELETE_USER_ROLE = "delete_user_role"
    MANAGE_USERS = "manage_users"
    MANAGE_DEPARTMENTS = "manage_departments"
    CREATE_USER_DEPARTMENT = "create_user_department"
    VIEW_USER_DEPARTMENT = "view_user_department"
    UPDATE_USER_DEPARTMENT = "update_user_department"
    DELETE_USER_DEPARTMENT = "delete_user_department"
    SYSTEM_CONFIGURATION = "system_configuration"
    DELETE_TIME_CORRECTION = "delete_time_correction"
    CREATE_ROLE = "create_role"
    VIEW_ROLE = "view_role"
    UPDATE_ROLE = "update_role"
    DELETE_ROLE = "delete_role"
    CREATE_LOGS = "create_logs"
    
    # Super Admin permissions
    ALL_PERMISSIONS = "all_permissions"